### ISSUE TITLE
Adding a Github Action to release to Github Pages

### ISSUE THREAD

**Issue by ShouvikGhosh2048** [karl-zylinski/odin-raylib-hot-reload-game-template#22]
Adding a Github action to directly release to Github pages would be nice.

I tried setting it up on a [fork](https://github.com/ShouvikGhosh2048/odin-raylib-hot-reload-game-template). I used [eframe_template](https://github.com/emilk/eframe_template) as reference.

- We create a `build_github_pages.sh`:
```bash
#!/bin/bash

# See https://github.com/karl-zylinski/odin-raylib-web for more examples on how
# to do a web build, including how to embed assets into it.

git clone https://github.com/emscripten-core/emsdk.git
./emsdk/emsdk install latest
./emsdk/emsdk activate latest

EMSCRIPTEN_SDK_DIR="emsdk"
OUT_DIR="game_web"

mkdir -p $OUT_DIR

export EMSDK_QUIET=1
# shellcheck disable=SC1091
[[ -f "$EMSCRIPTEN_SDK_DIR/emsdk_env.sh" ]] && . "$EMSCRIPTEN_SDK_DIR/emsdk_env.sh"

if ! odin-linux-amd64-nightly+2025-01-03/odin build main_web -target:freestanding_wasm32 -build-mode:obj -define:RAYLIB_WASM_LIB=env.o -vet -strict-style -o:speed -out:$OUT_DIR/game; then
  exit 1
fi

ODIN_PATH=$(odin-linux-amd64-nightly+2025-01-03/odin root)
files="main_web/main_web.c $OUT_DIR/game.wasm.o ${ODIN_PATH}/vendor/raylib/wasm/libraylib.a"
flags="-sUSE_GLFW=3 -sASYNCIFY -sASSERTIONS -DPLATFORM_WEB"
custom="--shell-file main_web/index_template.html"

# shellcheck disable=SC2086
# Add `-g` to `emcc` call to enable debug symbols (works in chrome).
emcc -g -o $OUT_DIR/index.html $files $flags $custom && rm $OUT_DIR/game.wasm.o

echo "Web build created in ${OUT_DIR}"
```
- We create a Github action `.github/workflows/pages.yml` (I'm using a specific odin nightly right now due to the recent raylib change, this can be updated once the change lands in dev-2025):
```
# Taken from https://github.com/emilk/eframe_template/blob/main/.github/workflows/pages.yml
name: Github Pages

# By default, runs if you push to main. keeps your deployed app in sync with main branch.
on:
  push:
    branches:
      - main
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # repo checkout
      - name: Download Odin (nightly)
        run: wget -qO- https://f001.backblazeb2.com/file/odin-binaries/nightly/odin-linux-amd64-nightly%2B2025-01-03.tar.gz | tar -xzf-
      - name: Download emscripten and build
        run: bash build_github_pages.sh # https://stackoverflow.com/a/74346752
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: game_web
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true
```
- Enable github pages as mentioned [here](https://github.com/emilk/eframe_template#web-deploy).

I managed to get it working [here](https://shouvikghosh2048.github.io/odin-raylib-hot-reload-game-template/), you can take a look.
